baseurl = "https://white-grass-05948d403.azurestaticapps.net/"
title = "Berkay Cinar"
theme = "hugo-coder"

[params]
  author = "Berkay Cinar"
  info = "Full Stack DevOps"
  description = "BerkayCinar's personal website"
  keywords = "blog,developer,personal"
  hideFooter = false
  hideCredits = false
  hideCopyright = false
  since = 2020

  colorScheme = "auto"

 # Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/berkaycinarrr/"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://linkedin.com/in/bcinar/"

  # Menu links
  [languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About me"
            weight = 1
            url = ""

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = ""

            [[languages.en.menu.main]]
            name = "Contact"
            weight = 3
            url = ""


    [languages.tr-tr]
        languagename = "Türkçe"
        title = "Berkay Çınar"

        [languages.tr-tr.params]
            author = "Berkay Çınar"
            info = "Full Stack DevOps"
            description = "Berkay Çınar'ın Kişisel Web Sitesi"
            keywords = "blog,yazılım,bilgisayar"

        [languages.tr-tr.menu]

            [[languages.tr-tr.menu.main]]
            name = "Hakkında"
            weight = 1
            url = ""

            [[languages.tr-tr.menu.main]]
            name = "Blog"
            weight = 2
            url = ""

            [[languages.tr-tr.menu.main]]
            name = "İletişim"
            weight = 3
            url = ""